### ISSUE TITLE
it doesn't build

### ISSUE THREAD

**Issue by iGOR121** [Disty0/android_kernel_xiaomi_toco#1]
`id1otina@pro:/media/building/android_kernel_xiaomi_toco/toolchain$ make  O=out ARCH=arm64 toco_user_defconfig #$DEFCONFIG
make: *** No rule to make target 'toco_user_defconfig'.  Stop.
`

**Comment by PoDameron** [comment]
cd ..&& make O=out ARCH=arm64 toco_user_defconfig

**Comment by PoDameron** [comment]
Always wypwd

**Comment by Disty0** [comment]
Script used to compile is in the readme. Also you are in the wrong folder.

**Comment by iGOR121** [comment]
oops, i was doing it in toolchain, lol
